### ISSUE TITLE
ghoori roadmap

### ISSUE THREAD

**Issue by Mamak-Y** [Ghoori/review-app#1]
- [ ] business categories (CRUD) + tests
- [ ] business entities (CRUD) + tests
- [ ] setup Devise for sign up, sign in and sign out
- [ ] test use sign up, sign in and sign out
- [ ] Review model and migration
- [ ] reviews controller (CRUD) + tests
- [ ] user activity model + migration
- [ ] create use activity on review actions
- [ ] user reputation management module
- [ ] authorization module
